# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5

install: pip install -U tox-travis

script: tox

# deploy:
#   provider: pypi
#   distributions: sdist bdist_wheel
#   user: cmeza99
#   password:
#     secure: PLEASE_REPLACE_ME
#   on:
#     tags: true
#     repo: cmeza99/async_query
#     python: 3.6
